### ISSUE TITLE
Any samples for Stripe Elements where we have subscription and add-on

### ISSUE THREAD

**Issue by techjewel** [stripe-samples/checkout-subscription-and-add-on#2]
I need a sample project like this where we have subscription + add-on optional where I want to to use Stripe Element.

**Comment by adreyfus-stripe** [comment]
Thanks for the suggestion @techjewel, adding to our backlog now and will update here when we have a sample published.

**Comment by techjewel** [comment]
Thanks it will be really great actually. I see lots of devs are confused about SCA and it's getting closer of the date.
Most of your samples are for checkout.js so this example for element.js will be very helpful.

**Comment by techjewel** [comment]
Hello @adreyfus-stripe 
Any update regarding this. 14th is near and I have to ship the plugin for my customers and users.

**Comment by adreyfus-stripe** [comment]
Hi @techjewel, apologies for the delay, we won't be able to get a sample out before September 14th due to other planned work but if you email plugins+sca@stripe.com outlining the flow you need we can try to get you help before the deadline.

**Comment by techjewel** [comment]
Thanks @adreyfus-stripe 
I could complete my plugin from the documentation. I already emailed **Chris Traganos** for review and showcase my WordPress plugin.

**Comment by willjosefi** [comment]
Heyo, I'm trying to find the same example but unfortunately I couldn't found
@techjewel have you been able to create this functionality using Elements?
