### ISSUE TITLE
Stripe CLI unable to install the sample 

### ISSUE THREAD

**Issue by magician25** [stripe-samples/checkout-subscription-and-add-on#7]
Stripe CLI is asking for client-and-server OR client-only. On choosing any, followed by php it is failing. There is no client-and-server directory (and rightly so) at /root/.config/stripe/samples-cache/checkout-subscription-and-add-on/ but stripe-cli is looking for it.

> stripe samples create checkout-subscription-and-add-on
✔ Finished downloading
✔ Selected integration: client-and-server
✔ Selected server: php
⣾ Copying files over... checkout-subscription-and-add-on lstat /root/.config/stripe/samples-cache/checkout-subscription-and-add-on/client-and-server/server/php: no such file or directory

**Comment by adreyfus-stripe** [comment]
@aakashrajvanshi Thanks for reporting! We just pushed out a fix in the latest version of the CLI that should fix this. Can you update your CLI to the latest version (1.2.4) and then try running again?
