### ISSUE TITLE
It's February 2020

### ISSUE THREAD

**Issue by chew-z** [stripe-samples/checkout-subscription-and-add-on#9]
Chrome 80 is here and 3rd party cookies are not cool anymore. Your hosted example isn't working by default anymore. 

https://blog.chromium.org/2019/10/developers-get-ready-for-new.html

**Comment by adreyfus-stripe** [comment]
@chew-z Yes, we're aware of third-party cookie policy change! This hosted example should still be working can you provide more details around the issue you're seeing?

**Comment by chew-z** [comment]
It is not working out of the box which might be surprising to some. I had to check console and allow 3-rd party cookies for the test site. After that it is working great ;-)

`A cookie associated with a cross-site resource at http://stripe.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`

I have been using Go example server.
